sfdx-source/apex-extensions/main/logger/objects/fflib_LogEntry__c/fields/LogLevel__c.field-meta.xml
<CustomField>
    <fullName>LogLevel__c</fullName>
    <description>The logging level</description>
    <label>Log Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/apex-extensions/tests/classes/MyTest.cls
/**
 * File Name: MyTest 
 * Description: 
 *
 * @author: architect ir. Wilhelmus G.J. Velzeboer | wvelzebo@its.jnj.com 
 */
public with sharing class MyTest
{

	public class WorkA extends fflib_DoWork
	{
		public void doWork()
		{
			System.debug('Work A executing');
			insert new fflib_LogEntry__c(
					LogLevel__c = 'INFO',
					Message__c = 'WorkA'
			);
		}
	}

	public class WorkB extends fflib_DoWork
	{
		public void doWork()
		{
			System.debug('Work B executing');
			insert new fflib_LogEntry__c(
					LogLevel__c = 'INFO',
					Message__c = 'WorkB'
			);
		}
	}

	public class WorkC extends fflib_DoWork
	{
		public void doWork()
		{
			System.debug('Work C executing');
			insert new fflib_LogEntry__c(
					LogLevel__c = 'INFO',
					Message__c = 'WorkC'
			);
		}
	}

}